/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

// Post-processed by post_process_typescript.js

// Enhanced post-processed - missing type definitions added
export type Allowedgeometrytypes = string[];
export type Alloweddatatypes = string[];
export type JSONSchema = any;
export interface Feature { type: "Feature"; geometry: Geometry; properties: Properties; }

export type Type = string;


/**
 * A DebriefFeature with constraints on geometry type and/or dataType.
 */
export interface GeometryConstrainedFeature {
  allowedGeometryTypes?: Allowedgeometrytypes;
  allowedDataTypes?: Alloweddatatypes;
  feature: Feature;
}
