/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


// Enhanced post-processed - missing type definitions added
export type Commits = any[];
export type JSONSchema = any;

/**
 * Collection of git commits for a tool.
 */
export interface GitHistory {
  commits?: Commits;
}
