/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


// Enhanced post-processed - missing type definitions added
export type Version = string;
export type Description2 = string;
export type Tools = any;
export type JSONSchema = any;
export type PackageInfo = any;

/**
 * Global index for all tools in a package (replaces generate_index_json() output).
 */
export interface GlobalToolIndexModel {
  tools: Tools;
  version: Version;
  description: Description2;
  /**
   * Optional package build metadata
   */
  packageInfo?: PackageInfo | null;
}
