/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

// Post-processed by post_process_typescript.js

// Enhanced post-processed - missing type definitions added
export type Description = string;
export type JSONSchemaType = string;
export type Additionalproperties = boolean;

export type Type = string;
export type Properties = { [key: string]: any; } | null;


/**
 * A JSON Schema object for defining data structure constraints.
 */
export interface JSONSchema {
  type?: JSONSchemaType | null;
  properties?: Properties;
  required?: Required;
  additionalProperties?: Additionalproperties;
  description?: Description;
}
