/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

// Post-processed by post_process_typescript.js

// Enhanced post-processed - missing type definitions added
export type Message = string;
export type Timestamp = string;
export type LogLevel = "debug" | "info" | "warning" | "error";
export type JSONSchema = any;

export type Payload = unknown[];


/**
 * Structured payload for logMessage command.
 */
export interface LogMessagePayload {
  message: Message;
  level?: LogLevel;
  timestamp?: Timestamp;
}
