/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


// Enhanced post-processed - missing type definitions added
export type Commit = string;
export type Author = string;
export type Builddate = string;
export type JSONSchema = any;

/**
 * Package build and metadata information.
 */
export interface PackageInfo {
  buildDate: Builddate;
  commit: Commit;
  author: Author;
}
