/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


// Enhanced post-processed - missing type definitions added
export type Name = string;
export type File = string;
export type Data = any;
export type JSONSchema = any;

/**
 * Sample input data for tool testing.
 */
export interface SampleInputData {
  name: Name;
  file: File;
  data: Data;
}
