/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

// Post-processed by post_process_typescript.js

// Enhanced post-processed - missing type definitions added
export type JSONSchema = any;
export interface ViewportState { bounds?: Bounds; center?: Position; zoom?: number; }

export type Command = string;


/**
 * Command to update the map viewport.
 */
export interface SetViewportCommand {
  command?: Command;
  payload: ViewportState;
}
