/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

// Post-processed by post_process_typescript.js

// Enhanced post-processed - missing type definitions added
export type JSONSchema = any;
export interface DebriefFeatureCollection { type?: Type; features: Features; bbox?: Bbox9; properties?: FeatureCollectionProperties | null; }

export type Command = string;


/**
 * Command to replace the entire feature collection.
 */
export interface SetFeatureCollectionCommand {
  command?: Command;
  payload: DebriefFeatureCollection;
}
