/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { ToolFileReference } from "./tool_file_reference";

// Enhanced post-processed - missing type definitions added
export type Description = string;
export type ToolName = string;
export type JSONSchema = any;
export type Inputs = Record<string, unknown>;
export type Schemas = Record<string, JSONSchema>;
export type SampleInputsCount = number;
export type GitCommitsCount = number;
export type SourceCodeLength = number;
export type ToolFileReference1 = ToolFileReference;
export type ToolFileReference2 = ToolFileReference;
export interface ToolFilesCollection { execute: ToolFileReference; source_code: ToolFileReference1; git_history: ToolFileReference2; inputs?: Inputs; schemas?: Schemas; }
export interface ToolStatsModel { sample_inputs_count?: SampleInputsCount; git_commits_count?: GitCommitsCount; source_code_length?: SourceCodeLength; }

/**
 * Index data for an individual tool (replaces packager.py:358-399 dictionary structure).
 */
export interface ToolIndexModel {
  tool_name: ToolName;
  description: Description;
  files: ToolFilesCollection;
  stats: ToolStatsModel;
}
