/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


// Enhanced post-processed - missing type definitions added
export type Inputs = any;
export type Schemas = any;
export type JSONSchema = any;
export interface ToolFileReference { path: Path; description: Description; type: Type; }
export interface ToolFileReference1 { path: Path; description: Description; type: Type; }
export interface ToolFileReference2 { path: Path; description: Description; type: Type; }

/**
 * Collection of files within a tool's directory structure.
 */
export interface ToolFilesCollection {
  execute: ToolFileReference;
  source_code: ToolFileReference1;
  git_history: ToolFileReference2;
  inputs?: Inputs;
  schemas?: Schemas;
}
