/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


// Enhanced post-processed - missing type definitions added
export type Name = string;
export type Description = string;
export type ToolUrl = string;
export type JSONSchema = any;
export type JSONSchema1 = any;
export type JSONSchemaProperty = Record<string, unknown>;

/**
 * A tool definition with input/output schemas for maritime analysis.
 */
export interface Tool {
  name: Name;
  description: Description;
  inputSchema: JSONSchema;
  /**
   * Optional JSON Schema defining the expected output format
   */
  outputSchema?: JSONSchema1 | null;
  tool_url?: ToolUrl;
}
