/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

// Post-processed by post_process_typescript.js

// Enhanced post-processed - missing type definitions added
export type Path = string;
export type Description = string;
export type JSONSchema = any;

export type Type = string;


/**
 * Reference to a file within a tool's directory structure.
 */
export interface ToolFileReference {
  path: Path;
  description: Description;
  type: Type;
}
