/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


// Enhanced post-processed - missing type definitions added
export type SampleInputsCount = number;
export type GitCommitsCount = number;
export type SourceCodeLength = number;
export type JSONSchema = any;

/**
 * Statistics about a tool's development and usage.
 */
export interface ToolStatsModel {
  sample_inputs_count?: SampleInputsCount;
  git_commits_count?: GitCommitsCount;
  source_code_length?: SourceCodeLength;
}
