/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A tool definition with input/output schemas for maritime analysis
 */
export interface Tool {
  /**
   * The unique identifier/name of the tool
   */
  name: string;
  /**
   * Human-readable description of what the tool does
   */
  description: string;
  inputSchema: JSONSchema;
  outputSchema?: JSONSchema1;
}
/**
 * JSON Schema defining the expected input parameters
 */
export interface JSONSchema {
  type?: "string" | "number" | "integer" | "boolean" | "object" | "array" | "null";
  properties?: {
    [k: string]: JSONSchemaProperty;
  };
  required?: string[];
  additionalProperties?: boolean | JSONSchemaProperty;
  description?: string;
  [k: string]: unknown;
}
export interface JSONSchemaProperty {
  type?: "string" | "number" | "integer" | "boolean" | "object" | "array" | "null";
  description?: string;
  enum?: unknown[];
  items?: JSONSchemaProperty;
  properties?: {
    [k: string]: JSONSchemaProperty;
  };
  required?: string[];
  additionalProperties?: boolean | JSONSchemaProperty;
  default?: unknown;
  [k: string]: unknown;
}
/**
 * Optional JSON Schema defining the expected output format
 */
export interface JSONSchema1 {
  type?: "string" | "number" | "integer" | "boolean" | "object" | "array" | "null";
  properties?: {
    [k: string]: JSONSchemaProperty;
  };
  required?: string[];
  additionalProperties?: boolean | JSONSchemaProperty;
  description?: string;
  [k: string]: unknown;
}
