/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { Tool } from "./tool";

// Enhanced post-processed - missing type definitions added
export type Version = string;
export type Description2 = string;
export type Tools = Tool[];
export type JSONSchema = any;

// Re-export Tool for convenience
export type { Tool };

/**
 * Response format for listing available tools.
 */
export interface ToolListResponse {
  tools: Tools;
  version?: Version;
  description?: Description2;
}
