/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

// Post-processed by post_process_typescript.js

// Enhanced post-processed - missing type definitions added
export type Name = string;
export type Description = string;
export type ModulePath = string;
export type ToolDir = string;
export type SourceCode = string;
export type SampleInputs = any[];
export type Parameters<T = any> = T;
export type ReturnType<T = any> = T;
export type JSONSchema = any;
export type GitHistory = any;

export type Type = string;


/**
 * Enhanced ToolMetadata class with typed parameters, sample_inputs, git_history.
 */
export interface ToolMetadataModel {
  name: Name;
  description: Description;
  parameters: Parameters;
  return_type: ReturnType;
  module_path: ModulePath;
  tool_dir: ToolDir;
  sample_inputs?: SampleInputs;
  source_code?: SourceCode;
  git_history?: GitHistory;
}
