/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

// Post-processed by post_process_typescript.js

// Enhanced post-processed - missing type definitions added
export type Iserror = boolean;
export type JSONSchema = any;
export type ToolVaultCommand = any;

export type Command = string;


/**
 * Response format for tool execution results containing ToolVault commands.
 */
export interface ToolCallResponse {
  result: ToolVaultCommand;
  isError?: Iserror;
}
