/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


// Enhanced post-processed - missing type definitions added
export type Name = string;
export type Arguments = any;
export type JSONSchema = any;

/**
 * Request model for tool call endpoint matching current Pydantic implementation.
 */
export interface ToolCallRequest {
  name: Name;
  arguments: Arguments;
}
