/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A GeoJSON Feature representing an annotation with any geometry type
 */
export interface DebriefAnnotationFeature {
  type: "Feature";
  /**
   * Unique identifier for this feature
   */
  id: string | number;
  geometry:
    | {
        type: "Point";
        /**
         * @minItems 2
         * @maxItems 3
         */
        coordinates: [number, number] | [number, number, number];
      }
    | {
        type: "LineString";
        /**
         * @minItems 2
         */
        coordinates: [
          [number, number] | [number, number, number],
          [number, number] | [number, number, number],
          ...([number, number] | [number, number, number])[]
        ];
      }
    | {
        type: "Polygon";
        /**
         * @minItems 1
         */
        coordinates: [
          [
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            ...([number, number] | [number, number, number])[]
          ],
          ...[
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            ...([number, number] | [number, number, number])[]
          ][]
        ];
      }
    | {
        type: "MultiPoint";
        coordinates: [number, number] | [number, number, number][];
      }
    | {
        type: "MultiLineString";
        /**
         * @minItems 1
         */
        coordinates: [
          [
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            ...([number, number] | [number, number, number])[]
          ],
          ...[
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            ...([number, number] | [number, number, number])[]
          ][]
        ];
      }
    | {
        type: "MultiPolygon";
        coordinates: [
          [
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            ...([number, number] | [number, number, number])[]
          ],
          ...[
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            ...([number, number] | [number, number, number])[]
          ][]
        ][];
      };
  properties: {
    /**
     * Discriminator to identify this as a zone feature
     */
    dataType: "zone";
    /**
     * Type of annotation
     */
    annotationType?: "label" | "area" | "measurement" | "comment" | "boundary";
    /**
     * Text content of the annotation
     */
    text?: string;
    /**
     * Color code in hex format
     */
    color?: string;
    /**
     * Timestamp when annotation was created
     */
    time?: string;
    /**
     * Human readable name for this annotation
     */
    name?: string;
    /**
     * Additional description or notes about this annotation
     */
    description?: string;
    [k: string]: unknown;
  };
}
