/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type { DebriefTrackFeature } from "./track";
import type { DebriefPointFeature } from "./point";
import type { DebriefAnnotationFeature } from "./annotation";

// Post-processed by post_process_typescript.js

// Enhanced post-processed - missing type definitions added
export type Bbox9 = Bbox;
export type FeatureCollectionProperties = { [key: string]: any; };
export type JSONSchema = any;

export type Bbox = [number, number, number, number] | [number, number, number, number, number, number];
export type Type = string;
export type Properties = { [key: string]: any; } | null;

// Union type for all Debrief features
export type DebriefFeature = DebriefTrackFeature | DebriefPointFeature | DebriefAnnotationFeature;
export type Features = DebriefFeature[];

// Re-export individual feature types for convenience
export type { DebriefTrackFeature, DebriefPointFeature, DebriefAnnotationFeature };


/**
 * A GeoJSON FeatureCollection containing mixed feature types for maritime analysis.
 */
export interface DebriefFeatureCollection {
  type?: Type;
  features: Features;
  bbox?: Bbox9;
  properties?: FeatureCollectionProperties | null;
}
