/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A GeoJSON Feature representing a point with time properties
 */
export interface DebriefPointFeature {
  type: "Feature";
  /**
   * Unique identifier for this feature
   */
  id: string | number;
  geometry: {
    type: "Point";
    /**
     * @minItems 2
     * @maxItems 3
     */
    coordinates: [number, number] | [number, number, number];
  };
  properties: {
    /**
     * Discriminator to identify this as a reference point feature
     */
    dataType: "reference-point";
    /**
     * Single timestamp for this point
     */
    time?: string;
    /**
     * Start time for a time range
     */
    timeStart?: string;
    /**
     * End time for a time range
     */
    timeEnd?: string;
    /**
     * Human readable name for this point
     */
    name?: string;
    /**
     * Additional description or notes for this point
     */
    description?: string;
    [k: string]: unknown;
  };
}
