/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A GeoJSON Feature representing a track with LineString or MultiLineString geometry and optional timestamps
 */
export interface DebriefTrackFeature {
  type: "Feature";
  /**
   * Unique identifier for this feature
   */
  id: string | number;
  geometry:
    | {
        type: "LineString";
        /**
         * @minItems 2
         */
        coordinates: [
          [number, number] | [number, number, number],
          [number, number] | [number, number, number],
          ...([number, number] | [number, number, number])[]
        ];
      }
    | {
        type: "MultiLineString";
        /**
         * @minItems 1
         */
        coordinates: [
          [
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            ...([number, number] | [number, number, number])[]
          ],
          ...[
            [number, number] | [number, number, number],
            [number, number] | [number, number, number],
            ...([number, number] | [number, number, number])[]
          ][]
        ];
      };
  properties: {
    /**
     * Discriminator to identify this as a track feature
     */
    dataType: "track";
    /**
     * Optional array of timestamps corresponding to each coordinate point
     */
    timestamps?: string[];
    /**
     * Human readable name for this track
     */
    name?: string;
    /**
     * Additional description or notes about this track
     */
    description?: string;
    [k: string]: unknown;
  };
}
