name: 'Build VS Code Extension'
description: 'Build and package VS Code extension'
inputs:
  ref:
    description: 'Git ref to checkout'
    required: false
    default: ''
  artifact_retention_days:
    description: 'Days to retain the artifact'
    required: false
    default: '7'

outputs:
  artifact_name:
    description: 'Name of the uploaded artifact'
    value: 'debrief-vsix'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm
    
    - name: Install dependencies
      shell: bash
      run: pnpm install --no-frozen-lockfile
    
    - name: Build VS Code extension and dependencies
      shell: bash
      run: pnpm build:vs-code
    
    - name: Install vsce
      shell: bash
      working-directory: apps/vs-code
      run: |
        # Install vsce with fallback to local installation
        pnpm add -g @vscode/vsce || pnpm add @vscode/vsce
    
    - name: Package extension
      shell: bash
      working-directory: apps/vs-code
      run: |
        # Package the extension with pnpm workspace compatibility
        # Use --no-dependencies to skip npm list validation since we're using pnpm
        if which vsce > /dev/null 2>&1; then
          vsce package --out extension.vsix --no-dependencies
        else
          npx vsce package --out extension.vsix --no-dependencies
        fi
        
        # Verify package was created
        if [ -f extension.vsix ]; then
          echo "✅ Extension packaged successfully"
          ls -la *.vsix
        else
          echo "❌ Extension packaging failed"
          exit 1
        fi
    
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: debrief-vsix
        path: apps/vs-code/extension.vsix
        retention-days: ${{ inputs.artifact_retention_days }}