/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

// Post-processed by post_process_typescript.js

// Enhanced post-processed - missing type definitions added
export type JSONSchema = any;

export type Editorid = string;
export type Filename = string;
export type Historycount = number;
import type { EditorState } from "./editor_state";


/**
 * Complete current state information for a Debrief editor including metadata.
 */
export interface CurrentState {
  editorId: Editorid;
  filename: Filename;
  editorState: EditorState;
  historyCount: Historycount;
}
