/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

// Post-processed by post_process_typescript.js
import type { DebriefFeatureCollection } from "../features/debrief_feature_collection";
import type { TimeState } from "./time_state";
import type { ViewportState } from "./viewport_state";
import type { SelectionState } from "./selection_state";

// Enhanced post-processed - missing type definitions added
export type JSONSchema = any;

/**
 * Aggregated state for a Debrief editor instance containing all sub-state types.
 */
export interface EditorState {
  /**
   * The GeoJSON FeatureCollection data
   */
  featureCollection?: DebriefFeatureCollection | null;
  /**
   * Current time position state
   */
  timeState?: TimeState | null;
  /**
   * Current map viewport bounds state
   */
  viewportState?: ViewportState | null;
  /**
   * Current feature selection state
   */
  selectionState?: SelectionState | null;
}
