/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * State representing the currently selected features in a Debrief editor
 */
export interface SelectionState {
  /**
   * Array of selected feature IDs
   */
  selectedIds: (string | number)[];
}
