/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * State representing the current time position in a Debrief editor
 */
export interface TimeState {
  /**
   * Current time position as ISO 8601 date-time string
   */
  current: string;
  /**
   * Start time of the overall time range as ISO 8601 date-time string
   */
  start: string;
  /**
   * End time of the overall time range as ISO 8601 date-time string
   */
  end: string;
}
