/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


// Enhanced post-processed - missing type definitions added
export type Current = string | number;
export type Start = string | number;
export type End = string | number;
export type JSONSchema = any;

/**
 * State representing the current time position in a Debrief editor.
 */
export interface TimeState {
  current: Current;
  start: Start;
  end: End;
}
