/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */


// Enhanced post-processed - missing type definitions added
export type Bounds = [number, number, number, number];
export type JSONSchema = any;

/**
 * State representing the current map viewport bounds in a Debrief editor.
 */
export interface ViewportState {
  bounds: Bounds;
}
