/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * State representing the current map viewport bounds in a Debrief editor
 */
export interface ViewportState {
  /**
   * Map bounds as [west, south, east, north] in decimal degrees
   *
   * @minItems 4
   * @maxItems 4
   */
  bounds: [number, number, number, number];
}
