/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * State representing the current time position in a Debrief editor
 */
export interface TimeState {
  /**
   * Current time position as ISO 8601 date-time string
   */
  current: string;
  /**
   * The overall time range of the data, as a [start, end] tuple of ISO 8601 date-time strings
   *
   * @minItems 2
   * @maxItems 2
   */
  range: [string, string];
}
